"""initial_schema

Revision ID: d8c718064db2
Revises: 
Create Date: 2026-08-08 20:10:51.981320
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8c718064db2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_roles',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_roles')),
    sa.UniqueConstraint('name', name='uq_job_roles_name')
    )
    op.create_index('idx_job_roles_active', 'job_roles', ['is_active'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('uq_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('read_at IS NULL OR is_read = true', name=op.f('ck_notifications_chk_notification_read_at')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notifications_reference', 'notifications', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_notifications_user_created', 'notifications', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', sa.text('created_at DESC')], unique=False, postgresql_where=sa.text('is_read = false'))
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_password_reset_tokens_chk_password_reset_token_expiry')),
    sa.CheckConstraint('used_at IS NULL OR used_at >= created_at', name=op.f('ck_password_reset_tokens_chk_password_reset_token_used')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_password_reset_token_hash')
    )
    op.create_index('idx_password_reset_tokens_active', 'password_reset_tokens', ['user_id', 'expires_at'], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_index('idx_password_reset_tokens_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index('idx_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_refresh_tokens_chk_refresh_token_expiry')),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name=op.f('ck_refresh_tokens_chk_refresh_token_revocation')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_token_hash')
    )
    op.create_index('idx_refresh_tokens_active', 'refresh_tokens', ['user_id', 'expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_version_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('current_version_number >= 1', name=op.f('ck_resumes_chk_resumes_version')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes')),
    sa.UniqueConstraint('user_id', name='uq_resumes_user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_organization', sa.String(length=200), nullable=True),
    sa.Column('current_designation', sa.String(length=150), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('profile_photo_path', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('years_of_experience IS NULL OR years_of_experience >= 0', name=op.f('ck_user_profiles_chk_user_profiles_experience')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    op.create_index('idx_user_profiles_organization', 'user_profiles', ['current_organization'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_roles_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_index('idx_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes >= 0', name=op.f('ck_resume_versions_chk_resume_file_size')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_resume_versions_chk_resume_version_number')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_versions_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_versions')),
    sa.UniqueConstraint('resume_id', 'version_number', name='uq_resume_version')
    )
    op.create_index('idx_resume_versions_current', 'resume_versions', ['resume_id', 'is_current'], unique=False)
    op.create_index('idx_resume_versions_resume_id', 'resume_versions', ['resume_id'], unique=False)
    op.create_index('uq_one_current_resume_version', 'resume_versions', ['resume_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_table('interviews',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('job_role_id', sa.UUID(), nullable=True),
    sa.Column('resume_version_id', sa.UUID(), nullable=True),
    sa.Column('interview_type', sa.String(length=30), nullable=False),
    sa.Column('practice_type', sa.String(length=30), nullable=True),
    sa.Column('role_name_snapshot', sa.String(length=150), nullable=True),
    sa.Column('job_description_snapshot', sa.Text(), nullable=True),
    sa.Column('role_requirements_snapshot', sa.Text(), nullable=True),
    sa.Column('required_experience_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('required_experience_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('access_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("(interview_type = 'PRACTICE' AND practice_type IS NOT NULL) OR (interview_type = 'ASSIGNED' AND practice_type IS NULL)", name=op.f('ck_interviews_chk_practice_configuration')),
    sa.CheckConstraint("interview_type IN ('PRACTICE', 'ASSIGNED')", name=op.f('ck_interviews_chk_interview_type')),
    sa.CheckConstraint("practice_type IS NULL OR practice_type IN ('JD_BASED', 'ROLE_BASED')", name=op.f('ck_interviews_chk_practice_type')),
    sa.CheckConstraint("status IN ('DRAFT', 'ASSIGNED', 'SCHEDULED', 'AVAILABLE', 'IN_PROGRESS', 'SUBMITTED', 'AI_EVALUATED', 'ADMIN_REVIEW', 'COMPLETED', 'CANCELLED', 'EXPIRED')", name=op.f('ck_interviews_chk_interview_status')),
    sa.CheckConstraint('(required_experience_min IS NULL OR required_experience_min >= 0) AND (required_experience_max IS NULL OR required_experience_max >= 0) AND (required_experience_min IS NULL OR required_experience_max IS NULL OR required_experience_max >= required_experience_min)', name=op.f('ck_interviews_chk_interview_experience')),
    sa.CheckConstraint('access_start_at IS NULL OR access_end_at IS NULL OR access_end_at > access_start_at', name=op.f('ck_interviews_chk_interview_access_window')),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 180', name=op.f('ck_interviews_chk_interview_duration')),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_interviews_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], name=op.f('fk_interviews_candidate_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], name=op.f('fk_interviews_job_role_id_job_roles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_interviews_resume_version_id_resume_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    op.create_index('idx_interviews_assigned_by', 'interviews', ['assigned_by'], unique=False)
    op.create_index('idx_interviews_candidate', 'interviews', ['candidate_id'], unique=False)
    op.create_index('idx_interviews_job_role', 'interviews', ['job_role_id'], unique=False)
    op.create_index('idx_interviews_resume_version', 'interviews', ['resume_version_id'], unique=False)
    op.create_index('idx_interviews_scheduled_at', 'interviews', ['scheduled_at'], unique=False)
    op.create_index('idx_interviews_status', 'interviews', ['status'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_question_number', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'NOT_STARTED'"), nullable=False),
    sa.Column('interview_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('NOT_STARTED', 'IN_PROGRESS', 'PAUSED', 'SUBMITTED', 'EVALUATING', 'EVALUATED', 'COMPLETED', 'ABANDONED')", name=op.f('ck_interview_sessions_chk_session_status')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_interview_sessions_chk_attempt_number')),
    sa.CheckConstraint('current_question_number >= 0', name=op.f('ck_interview_sessions_chk_session_question_number')),
    sa.CheckConstraint('ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at', name=op.f('ck_interview_sessions_chk_session_time')),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_interview_sessions_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_sessions')),
    sa.UniqueConstraint('interview_id', 'attempt_number', name='uq_interview_attempt')
    )
    op.create_index('idx_interview_sessions_interview_id', 'interview_sessions', ['interview_id'], unique=False)
    op.create_index('idx_interview_sessions_status', 'interview_sessions', ['status'], unique=False)
    op.create_table('final_decisions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ai_verdict', sa.String(length=30), nullable=True),
    sa.Column('ai_overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('ai_weaknesses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('ai_improvement_areas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('admin_decision', sa.String(length=30), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("admin_decision IS NULL OR admin_decision IN ('CLEARED', 'NOT_CLEARED', 'NEEDS_FURTHER_REVIEW')", name=op.f('ck_final_decisions_chk_admin_decision')),
    sa.CheckConstraint("ai_verdict IS NULL OR ai_verdict IN ('CLEARED', 'NOT_CLEARED', 'BORDERLINE', 'NEEDS_REVIEW')", name=op.f('ck_final_decisions_chk_final_ai_verdict')),
    sa.CheckConstraint('ai_overall_score IS NULL OR (ai_overall_score >= 0 AND ai_overall_score <= 10)', name=op.f('ck_final_decisions_chk_final_ai_score')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_final_decisions_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_final_decisions_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_final_decisions')),
    sa.UniqueConstraint('session_id', name='uq_final_decision_session')
    )
    op.create_index('idx_final_decisions_admin_decision', 'final_decisions', ['admin_decision'], unique=False)
    op.create_index('idx_final_decisions_decided_by', 'final_decisions', ['decided_by'], unique=False)
    op.create_index('idx_final_decisions_session', 'final_decisions', ['session_id'], unique=False)
    op.create_table('interview_events',
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("event_type IN ('INTERVIEW_CREATED', 'INTERVIEW_ASSIGNED', 'INTERVIEW_SCHEDULED', 'INTERVIEW_RESCHEDULED', 'INTERVIEW_CANCELLED', 'INTERVIEW_STARTED', 'INTERVIEW_PAUSED', 'INTERVIEW_RESUMED', 'QUESTION_ASKED', 'ANSWER_STARTED', 'ANSWER_SUBMITTED', 'CODING_SUBMISSION', 'INTERVIEW_SUBMITTED', 'AI_EVALUATION_STARTED', 'AI_EVALUATION_COMPLETED', 'ADMIN_REVIEW_STARTED', 'ADMIN_DECISION_MADE', 'RESULT_PUBLISHED', 'INTERVIEW_EXPIRED')", name=op.f('ck_interview_events_chk_interview_event_type')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_interview_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_interview_events_interview_id_interviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_events_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_events'))
    )
    op.create_index('idx_interview_events_actor', 'interview_events', ['actor_user_id'], unique=False)
    op.create_index('idx_interview_events_created_at', 'interview_events', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_interview_events_interview', 'interview_events', ['interview_id', 'created_at'], unique=False)
    op.create_index('idx_interview_events_session', 'interview_events', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_interview_events_type', 'interview_events', ['event_type'], unique=False)
    op.create_table('interview_questions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('topic', sa.String(length=150), nullable=True),
    sa.Column('skill', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=30), server_default=sa.text("'AI_GENERATED'"), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('evaluation_rubric', sa.Text(), nullable=True),
    sa.Column('question_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("difficulty IS NULL OR difficulty IN ('EASY', 'MEDIUM', 'HARD')", name=op.f('ck_interview_questions_chk_question_difficulty')),
    sa.CheckConstraint("question_type IN ('TECHNICAL', 'PROJECT', 'BEHAVIORAL', 'CODING', 'SYSTEM_DESIGN', 'FOLLOW_UP')", name=op.f('ck_interview_questions_chk_question_type')),
    sa.CheckConstraint("source IN ('AI_GENERATED', 'INTERVIEWER_CREATED', 'QUESTION_BANK')", name=op.f('ck_interview_questions_chk_question_source')),
    sa.CheckConstraint('question_number >= 1', name=op.f('ck_interview_questions_chk_question_number')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_questions_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_questions')),
    sa.UniqueConstraint('session_id', 'question_number', name='uq_question_number')
    )
    op.create_index('idx_interview_questions_session', 'interview_questions', ['session_id'], unique=False)
    op.create_index('idx_interview_questions_skill', 'interview_questions', ['skill'], unique=False)
    op.create_index('idx_interview_questions_type', 'interview_questions', ['question_type'], unique=False)
    op.create_table('skill_scores',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('10'), nullable=False),
    sa.Column('strength', sa.Text(), nullable=True),
    sa.Column('improvement_area', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('max_score > 0', name=op.f('ck_skill_scores_chk_skill_max_score')),
    sa.CheckConstraint('score >= 0 AND score <= max_score', name=op.f('ck_skill_scores_chk_skill_score')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_skill_scores_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_scores')),
    sa.UniqueConstraint('session_id', 'skill_name', name='uq_skill_score')
    )
    op.create_index('idx_skill_scores_session', 'skill_scores', ['session_id'], unique=False)
    op.create_index('idx_skill_scores_skill', 'skill_scores', ['skill_name'], unique=False)
    op.create_table('interview_answers',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('answer_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('response_time_seconds IS NULL OR response_time_seconds >= 0', name=op.f('ck_interview_answers_chk_answer_response_time')),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], name=op.f('fk_interview_answers_question_id_interview_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_answers')),
    sa.UniqueConstraint('question_id', name='uq_interview_answer_question')
    )
    op.create_index('idx_interview_answers_submitted', 'interview_answers', ['is_submitted'], unique=False)
    op.create_table('interview_evaluations',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('evaluation_type', sa.String(length=30), nullable=False),
    sa.Column('correctness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reasoning_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_verdict', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('improvement_areas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('evaluation_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("(evaluation_type = 'QUESTION' AND question_id IS NOT NULL) OR (evaluation_type = 'FINAL' AND question_id IS NULL)", name=op.f('ck_interview_evaluations_chk_evaluation_question_scope')),
    sa.CheckConstraint("ai_verdict IS NULL OR ai_verdict IN ('CLEARED', 'NOT_CLEARED', 'BORDERLINE', 'NEEDS_REVIEW')", name=op.f('ck_interview_evaluations_chk_evaluation_verdict')),
    sa.CheckConstraint("evaluation_type IN ('QUESTION', 'FINAL')", name=op.f('ck_interview_evaluations_chk_evaluation_type')),
    sa.CheckConstraint('(correctness_score IS NULL OR (correctness_score >= 0 AND correctness_score <= 10)) AND (technical_score IS NULL OR (technical_score >= 0 AND technical_score <= 10)) AND (communication_score IS NULL OR (communication_score >= 0 AND communication_score <= 10)) AND (reasoning_score IS NULL OR (reasoning_score >= 0 AND reasoning_score <= 10)) AND (overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 10))', name=op.f('ck_interview_evaluations_chk_evaluation_scores')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_interview_evaluations_chk_evaluation_confidence')),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], name=op.f('fk_interview_evaluations_question_id_interview_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_evaluations_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_evaluations'))
    )
    op.create_index('idx_interview_evaluations_question', 'interview_evaluations', ['question_id'], unique=False)
    op.create_index('idx_interview_evaluations_session', 'interview_evaluations', ['session_id'], unique=False)
    op.create_index('idx_interview_evaluations_type', 'interview_evaluations', ['evaluation_type'], unique=False)
    op.create_index('uq_final_evaluation', 'interview_evaluations', ['session_id'], unique=True, postgresql_where=sa.text("evaluation_type = 'FINAL'"))
    op.create_index('uq_question_evaluation', 'interview_evaluations', ['session_id', 'question_id'], unique=True, postgresql_where=sa.text("evaluation_type = 'QUESTION'"))
    op.create_table('coding_submissions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('execution_status', sa.String(length=30), nullable=True),
    sa.Column('test_cases_passed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('test_cases_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('execution_time_ms', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('memory_used_mb', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('is_final_submission', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("execution_status IS NULL OR execution_status IN ('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'TIMEOUT', 'MEMORY_LIMIT', 'RUNTIME_ERROR', 'COMPILE_ERROR')", name=op.f('ck_coding_submissions_chk_coding_execution_status')),
    sa.CheckConstraint('execution_time_ms IS NULL OR execution_time_ms >= 0', name=op.f('ck_coding_submissions_chk_coding_execution_time')),
    sa.CheckConstraint('memory_used_mb IS NULL OR memory_used_mb >= 0', name=op.f('ck_coding_submissions_chk_coding_memory')),
    sa.CheckConstraint('test_cases_passed >= 0 AND test_cases_total >= 0 AND test_cases_passed <= test_cases_total', name=op.f('ck_coding_submissions_chk_coding_test_cases')),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], name=op.f('fk_coding_submissions_answer_id_interview_answers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], name=op.f('fk_coding_submissions_question_id_interview_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coding_submissions'))
    )
    op.create_index('idx_coding_submissions_answer', 'coding_submissions', ['answer_id'], unique=False)
    op.create_index('idx_coding_submissions_question', 'coding_submissions', ['question_id'], unique=False)
    op.create_index('idx_coding_submissions_submitted_at', 'coding_submissions', ['submitted_at'], unique=False)
    op.create_index('uq_coding_final_submission', 'coding_submissions', ['question_id'], unique=True, postgresql_where=sa.text('is_final_submission = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_coding_final_submission', table_name='coding_submissions', postgresql_where=sa.text('is_final_submission = true'))
    op.drop_index('idx_coding_submissions_submitted_at', table_name='coding_submissions')
    op.drop_index('idx_coding_submissions_question', table_name='coding_submissions')
    op.drop_index('idx_coding_submissions_answer', table_name='coding_submissions')
    op.drop_table('coding_submissions')
    op.drop_index('uq_question_evaluation', table_name='interview_evaluations', postgresql_where=sa.text("evaluation_type = 'QUESTION'"))
    op.drop_index('uq_final_evaluation', table_name='interview_evaluations', postgresql_where=sa.text("evaluation_type = 'FINAL'"))
    op.drop_index('idx_interview_evaluations_type', table_name='interview_evaluations')
    op.drop_index('idx_interview_evaluations_session', table_name='interview_evaluations')
    op.drop_index('idx_interview_evaluations_question', table_name='interview_evaluations')
    op.drop_table('interview_evaluations')
    op.drop_index('idx_interview_answers_submitted', table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index('idx_skill_scores_skill', table_name='skill_scores')
    op.drop_index('idx_skill_scores_session', table_name='skill_scores')
    op.drop_table('skill_scores')
    op.drop_index('idx_interview_questions_type', table_name='interview_questions')
    op.drop_index('idx_interview_questions_skill', table_name='interview_questions')
    op.drop_index('idx_interview_questions_session', table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index('idx_interview_events_type', table_name='interview_events')
    op.drop_index('idx_interview_events_session', table_name='interview_events')
    op.drop_index('idx_interview_events_interview', table_name='interview_events')
    op.drop_index('idx_interview_events_created_at', table_name='interview_events')
    op.drop_index('idx_interview_events_actor', table_name='interview_events')
    op.drop_table('interview_events')
    op.drop_index('idx_final_decisions_session', table_name='final_decisions')
    op.drop_index('idx_final_decisions_decided_by', table_name='final_decisions')
    op.drop_index('idx_final_decisions_admin_decision', table_name='final_decisions')
    op.drop_table('final_decisions')
    op.drop_index('idx_interview_sessions_status', table_name='interview_sessions')
    op.drop_index('idx_interview_sessions_interview_id', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index('idx_interviews_status', table_name='interviews')
    op.drop_index('idx_interviews_scheduled_at', table_name='interviews')
    op.drop_index('idx_interviews_resume_version', table_name='interviews')
    op.drop_index('idx_interviews_job_role', table_name='interviews')
    op.drop_index('idx_interviews_candidate', table_name='interviews')
    op.drop_index('idx_interviews_assigned_by', table_name='interviews')
    op.drop_table('interviews')
    op.drop_index('uq_one_current_resume_version', table_name='resume_versions', postgresql_where=sa.text('is_current = true'))
    op.drop_index('idx_resume_versions_resume_id', table_name='resume_versions')
    op.drop_index('idx_resume_versions_current', table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index('idx_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_user_profiles_organization', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('resumes')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_active', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('refresh_tokens')
    op.drop_index('idx_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_expires_at', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_active', table_name='password_reset_tokens', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_notifications_user_unread', table_name='notifications', postgresql_where=sa.text('is_read = false'))
    op.drop_index('idx_notifications_user_created', table_name='notifications')
    op.drop_index('idx_notifications_reference', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('idx_job_roles_active', table_name='job_roles')
    op.drop_table('job_roles')
    # ### end Alembic commands ###
